
        hyperparameter: {
          optimization: {
            method: Adam,
            learning_rate: 0.01
          },

          batch_size: 512,
          max_epoch: 50,
          regularizer_l2: 0.001,

          perplexity: 5, 
          seed: 1
        }

        architecture: {
          latent_dimension: 2, 